import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import MouseReactiveBackground from "@/components/MouseReactiveBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MouseReactiveBackground/>
      <body
        className={`antialiased lg:w-3/4 lg:mx-auto mx-2 dark`}
      >
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
